@baseUrl = http://localhost:4004/
@svc = odata/v4/galaxy/

### Service Document
GET {{baseUrl}}/{{svc}}
Accept: application/json
Authorization: Basic YWRtaW51c2VyOmFiY2QxMjM0

### Metadata
GET {{baseUrl}}/{{svc}}/$metadata
Accept: application/xml
Authorization: Basic YWRtaW51c2VyOmFiY2QxMjM0

### Get all spacefarers (401 Unauthorized)
GET {{baseUrl}}/{{svc}}/Spacefarers?$count=true&$orderby=name
Accept: application/json

### Get all spacefarers (200 OK) as Admin on Planet X
GET {{baseUrl}}/{{svc}}/Spacefarers?$count=true&$orderby=name
Authorization: Basic YWRtaW51c2VyOmFiY2QxMjM0
Accept: application/json

### Create a new spacefarer
# @name createSpacefarer
POST {{baseUrl}}/{{svc}}/Spacefarers
Content-Type: application/json
Accept: application/json
Authorization: Basic YWRtaW51c2VyOmFiY2QxMjM0

{
  "name": "Lyra Vega",
  "stardustCollection": 20,
  "wormholeNavigationSkill": 3,
  "totalMerit": 0,
  "originPlanet_code": "PX",
  "department_code": "EXP",
  "position_code": "NAV",
  "spacesuitColor_code": "COB"
}

### Failes to create a new spacefarer as a non-admin user (403 Forbidden)
# @name createSpacefarer
POST {{baseUrl}}/{{svc}}/Spacefarers
Content-Type: application/json
Accept: application/json
Authorization: Basic dmlld2VyOmFiY2QxMjM0

{
  "name": "Lyra Vega",
  "stardustCollection": 20,
  "wormholeNavigationSkill": 3,
  "totalMerit": 0,
  "originPlanet": "Planet X",
  "department": "Exploration",
  "position": "Navigator",
  "spacesuitColor": "Cobalt"
}

### Create a new spacefarer with email as Admin on Planet X
POST {{baseUrl}}/{{svc}}/Spacefarers
Authorization: Basic YWRtaW51c2VyOmFiY2QxMjM0
Content-Type: application/json
Accept: application/json

{
"name": "Cassian Andor",
"stardustCollection": 20,
"wormholeNavigationSkill": 3,
"department_code":   "EXP",
"position_code":     "NAV",
"spacesuitColor_code": "COB",
"email": ""
}


### CREATE spacefarer (Admin) — should return 201 and an entity
# @name create_admin_spacefarer
POST {{baseUrl}}//{{svc}}/Spacefarers
Authorization: Basic YWRtaW51c2VyOmFiY2QxMjM0
Content-Type: application/json
Prefer: return=representation

{
  "name": "Test Pilot",
  "stardustCollection": 120,
  "wormholeNavigationSkill": 6
}
